// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accountsetting: typeof import('./src/components/accountsetting.vue')['default']
    AccountSetting: typeof import('./src/components/accountSetting.vue')['default']
    BaicInfo: typeof import('./src/components/baicInfo.vue')['default']
    BasicInfo: typeof import('./src/components/basicInfo.vue')['default']
    Basicsetting: typeof import('./src/components/basicsetting.vue')['default']
    BasicSetting: typeof import('./src/components/basicSetting.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Error404: typeof import('./src/components/error404.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    MainView: typeof import('./src/components/mainView.vue')['default']
    NormalTools: typeof import('./src/components/normalTools.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchGithub: typeof import('./src/components/searchGithub.vue')['default']
    SearchInput: typeof import('./src/components/searchInput.vue')['default']
    SearchLocal: typeof import('./src/components/searchLocal.vue')['default']
    ShowsearchInput: typeof import('./src/components/showsearchInput.vue')['default']
    UserInfoSetting: typeof import('./src/components/userInfoSetting.vue')['default']
    UserLikesList: typeof import('./src/components/userLikesList.vue')['default']
    WriteArticle: typeof import('./src/components/writeArticle.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
